version: '3.8'

services:
  db:
    image: postgres:latest
    build:
        context: ./db
        dockerfile: Dockerfile.pgsql
    container_name: db_container
    environment:
        POSTGRES_DB: employee-management
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 9191
    volumes:
        - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
        - "5432:5432"
    networks:
        - employee_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rmq_container
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - employee_network

  employeeservice:
    container_name: emp
    build:
      context: .
      dockerfile: EmployeeService/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - employee_network
    restart: on-failure

  storageservice:
    container_name: stor
    build:
        context: .
        dockerfile: StorageService/Dockerfile
    ports:
        - "5002:8080"
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - RabbitMQ__Host=rabbitmq
        - ConnectionStrings__PostgresSQL=Server=db;Port=5432;Database=employee-management;User Id=postgres;Password=9191
    depends_on:
        - rabbitmq
        - db
    networks:
        - employee_network
    restart: on-failure

networks:
  employee_network:
    external: true